
name: gh-pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 15 ]
        app_root: [ "mnt/app" ]

    runs-on: ${{ matrix.os }}

    steps:

      - name: checkout
        uses: actions/checkout@master

      - name: setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: cache node_modules
        uses: actions/cache@v2
        id: yarn-cache # use `steps.yarn-cache.outputs.cache-hit != 'true'`
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: |
          cd ${{ matrix.app_root }}
          yarn

      - name: run tests
        run: |
          cd ${{ matrix.app_root }}
          yarn test

      - name: generate
        run: |
          cd ${{ matrix.app_root }}
          yarn generate

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ matrix.app_root }}/dist
